### ISSUE TITLE
Running actions on closed & merged PRs

### ISSUE THREAD

**Issue by tiithansen** [reviewpad/reviewpad#524] opened 2022-12-12 14:52 UTC
**Is your feature request related to a problem? Please describe.**
Currently its not possible to remove labels or delete branches with Reviewpad if the PR has been closed or merged when Reviewpad is executed via Github Actions pipeline on "pull_request.closed" trigger.

**Describe the solution you'd like**
Allow running Reviewpad actions on closed & merged PRs by settings some option in github actions pipeline.

**Describe alternatives you've considered**
Alternative option could be to use actions from github martketplace, but this makes PR management pipelines messy.

**Comment by marcelosousa** [comment] 2022-12-12 17:18
Closing this issue as it is a duplicate of https://github.com/reviewpad/action/issues/52.

**Closed by marcelosousa** 2022-12-12 17:18 UTC
Labels: enhancement
