### ISSUE TITLE
Duplicated reviewpad report

### ISSUE THREAD

**Issue by shay2025** [reviewpad/reviewpad#102] opened 2022-07-12 10:18 UTC
**Describe the bug**
In this PR https://github.com/reviewpad/reviewpad/pull/101, it was generated 2 identical reviewpad reports.

**To Reproduce**
https://github.com/reviewpad/reviewpad/pull/101

**Expected behavior**
Only one reviewpad report should appear.

**Screenshots**
*None*

**Comment by marcelosousa** [comment] 2022-08-01 15:24
I couldn't reproduce this issue. Closing for now.

**Closed by marcelosousa** 2022-08-01 15:24 UTC
Labels: bug
