### ISSUE TITLE
Rebase unit tests are not working on MacOS

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#437] opened 2022-11-08 17:38 UTC
**Describe the bug**
Right now when running `task test` on mac os, the following errors appear:

```bash
=== Failed
=== FAIL: codehost/github TestRebaseOnto_WhenInitRebaseFails (0.01s)
    repo_test.go:419: 
                Error Trace:    /Users/tiago/dev/reviewpad/reviewpad/codehost/github/repo_test.go:419
                                                        /Users/tiago/dev/reviewpad/reviewpad/codehost/github/repo_test.go:187
                Error:          Fail at /Users/tiago/dev/reviewpad/reviewpad/codehost/github/repo_test.go:187; failed to write reference 'refs/heads/main': a reference with that name already exists.
                Test:           TestRebaseOnto_WhenInitRebaseFails

=== FAIL: codehost/github TestRebaseOnto_WhenRebaseCommitFails (0.02s)
    repo_test.go:239: 
                Error Trace:    /Users/tiago/dev/reviewpad/reviewpad/codehost/github/repo_test.go:239
                Error:          An error is expected but got nil.
                Test:           TestRebaseOnto_WhenRebaseCommitFails

=== FAIL: codehost/github TestPush (0.01s)
    repo_test.go:419: 
                Error Trace:    /Users/tiago/dev/reviewpad/reviewpad/codehost/github/repo_test.go:419
                                                        /Users/tiago/dev/reviewpad/reviewpad/codehost/github/repo_test.go:296
                Error:          Fail at /Users/tiago/dev/reviewpad/reviewpad/codehost/github/repo_test.go:296; failed to write reference 'refs/heads/main': a reference with that name already exists.
                Test:           TestPush

=== FAIL: plugins/aladino/actions TestRebase/when_checkout_branch_fails (0.01s)
2022/11/08 17:36:54 [info] cloning https://github.com/reviewpad/TestGitRepository to /var/folders/gj/tyynpnsn1nl42g7ryzc5_0br0000gn/T/repository617162056
    --- FAIL: TestRebase/when_checkout_branch_fails (0.01s)
panic: interface conversion: interface {} is *git.GitError, not string [recovered]
        panic: interface conversion: interface {} is *git.GitError, not string

goroutine 717 [running]:
testing.tRunner.func1.2({0x47e9d40, 0xc0002ff620})
        /Users/tiago/sdk/go1.18.2/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
        /Users/tiago/sdk/go1.18.2/src/testing/testing.go:1392 +0x39f
panic({0x47e9d40, 0xc0002ff620})
        /Users/tiago/sdk/go1.18.2/src/runtime/panic.go:838 +0x207
github.com/stretchr/testify/assert.messageFromMsgAndArgs({0xc000659f40?, 0xc000659e38?, 0xc000c19380?})
        /Users/tiago/go/pkg/mod/github.com/stretchr/testify@v1.8.0/assert/assertions.go:193 +0xff
github.com/stretchr/testify/assert.Fail({0x4a17d20, 0xc000c19380}, {0x4919518, 0x1f}, {0xc000659f40, 0x2, 0x2})
        /Users/tiago/go/pkg/mod/github.com/stretchr/testify@v1.8.0/assert/assertions.go:259 +0x217
github.com/stretchr/testify/assert.FailNow({0x4a17d20, 0xc000c19380}, {0x4919518, 0x1f}, {0xc000659f40, 0x2, 0x2})
        /Users/tiago/go/pkg/mod/github.com/stretchr/testify@v1.8.0/assert/assertions.go:226 +0x8a
github.com/reviewpad/reviewpad/v3/plugins/aladino/actions_test.TestRebase.func1(0x43453df?)
        /Users/tiago/dev/reviewpad/reviewpad/plugins/aladino/actions/rebase_test.go:96 +0x1c7
testing.tRunner(0xc000c19380, 0xc0004754e0)
        /Users/tiago/sdk/go1.18.2/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        /Users/tiago/sdk/go1.18.2/src/testing/testing.go:1486 +0x35f

=== FAIL: plugins/aladino/actions TestRebase (0.02s)
```

**To Reproduce**
1. Open the project on MacOS
2. Run `task test`
3. You should see the tests failing with the error described above.

**Expected behavior**
The tests shouldn't fail.

**Comment by marcelosousa** [comment] 2023-01-25 10:07
Duplicate of #409

**Closed by marcelosousa** 2023-01-25 10:07 UTC
Labels: bug
